CREATE TABLE IF NOT EXISTS "bpm_user_group" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status" tinyint NOT NULL,
    "user_ids" varchar(255) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '用户组';

CREATE TABLE IF NOT EXISTS "bpm_category" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "code" varchar(63) NOT NULL,
    "description" varchar(255) NOT NULL,
    "status" tinyint NOT NULL,
    "sort" int NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '分类';

CREATE TABLE IF NOT EXISTS "bpm_form" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(63) NOT NULL,
    "status" tinyint NOT NULL,
    "fields" varchar(255) NOT NULL,
    "conf" varchar(255) NOT NULL,
    "remark" varchar(255),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '动态表单';

CREATE TABLE IF NOT EXISTS "bpm_ai_approval_task" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "process_instance_id" varchar(128) NOT NULL,
    "process_definition_id" varchar(128) NOT NULL,
    "task_id" varchar(128) NOT NULL,
    "task_definition_key" varchar(128),
    "task_name" varchar(255),
    "assignee_user_id" bigint,
    "external_id" varchar(255) NOT NULL,
    "guanlan_task_id" varchar(128),
    "enabled" bit NOT NULL DEFAULT TRUE,
    "adopt_enabled" bit NOT NULL DEFAULT FALSE,
    "status" tinyint NOT NULL,
    "verdict" varchar(32),
    "opinion" varchar(1024),
    "callback_id" varchar(128),
    "callback_time" timestamp,
    "business_final_verdict" varchar(32),
    "business_final_opinion" varchar(1024),
    "business_result_sync_time" timestamp,
    "submit_error" varchar(500),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'BPM AI 审批任务';

CREATE UNIQUE INDEX IF NOT EXISTS "uk_bpm_ai_task_tenant_task"
    ON "bpm_ai_approval_task" ("tenant_id", "task_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_bpm_ai_task_tenant_external"
    ON "bpm_ai_approval_task" ("tenant_id", "external_id");

CREATE TABLE IF NOT EXISTS "bpm_ai_approval_callback_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "callback_id" varchar(128) NOT NULL,
    "guanlan_task_id" varchar(128),
    "external_id" varchar(255),
    "verdict" varchar(32),
    "test_mode" bit NOT NULL DEFAULT FALSE,
    "verified" bit NOT NULL DEFAULT FALSE,
    "processed" bit NOT NULL DEFAULT FALSE,
    "raw_body" clob,
    "error_message" varchar(500),
    "received_time" timestamp NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'BPM AI 审批回调日志';

CREATE UNIQUE INDEX IF NOT EXISTS "uk_bpm_ai_callback_tenant_callback"
    ON "bpm_ai_approval_callback_log" ("tenant_id", "callback_id");
